module "single_server_asg" {
  source = "git@github.com:terraform-aws-modules/terraform-aws-autoscaling.git?ref=v6.5.0"

  name                                 = var.asg_name
  max_size                             = var.asg_max_size
  min_size                             = var.asg_min_size
  desired_capacity                     = var.asg_desired_capacity
  key_name                             = var.asg_key_name
  instance_type                        = var.asg_instance_type
  vpc_zone_identifier                  = var.asg_vpc_zone_identifier
  availability_zones                   = var.asg_availability_zones
  disable_api_termination              = var.asg_disable_api_termination
  ebs_optimized                        = var.asg_ebs_optimized
  force_delete                         = var.asg_force_delete
  health_check_grace_period            = var.asg_health_check_grace_period
  health_check_type                    = var.asg_health_check_type
  instance_initiated_shutdown_behavior = var.asg_instance_initiated_shutdown_behavior
  max_instance_lifetime                = var.asg_max_instance_lifetime
  user_data                            = var.asg_user_data
  use_name_prefix                      = var.asg_use_name_prefix
  tags                                 = var.asg_tags

  # default_cooldown                     = ""
  # capacity_rebalance                   = ""
  # default_version                      = ""
  # delete_timeout                       = ""
  # iam_instance_profile_arn  = ""
  # iam_instance_profile_name = ""
  # iam_role_name             = ""
  # iam_role_path                        = ""
  # iam_role_permissions_boundary        = ""
  # kernel_id                            = ""
  # launch_template         = ""
  # launch_template_version = ""
  # metrics_granularity = ""
  # min_elb_capacity                     = ""
  # mixed_instances_policy               = ""
  # placement_group                      = ""
  # ram_disk_id                          = ""
  # service_linked_role_arn              = ""
  # update_default_version = ""
  # wait_for_capacity_timeout            = ""
  # wait_for_elb_capacity                = ""

  # autoscaling_group_tags             = ""
  # block_device_mappings              = ""
  # capacity_reservation_specification = ""
  # cpu_options                        = ""
  # create                             = ""
  # create_iam_instance_profile        = ""
  # create_launch_template             = ""
  # create_scaling_policy              = ""
  # create_schedule                    = ""
  # credit_specification               = ""
  # elastic_gpu_specifications         = ""
  # elastic_inference_accelerator      = ""
  # enable_monitoring                  = ""
  # enabled_metrics                    = ""
  # enclave_options                    = ""
  # hibernation_options                = ""
  # iam_role_policies                  = ""
  # iam_role_tags                      = ""
  # iam_role_use_name_prefix           = ""
  # ignore_desired_capacity_changes    = ""
  # image_id                           = ""
  # initial_lifecycle_hooks            = ""
  # instance_market_options            = ""
  # instance_name                      = ""
  # instance_refresh                   = ""
  # instance_requirements              = ""
  # launch_template_name               = ""
  # launch_template_use_name_prefix    = ""
  # license_specifications             = ""
  # load_balancers                     = ""
  # maintenance_options                = ""
  # metadata_options                   = ""
  # network_interfaces                 = ""
  # placement                          = ""
  # private_dns_name_options           = ""
  # protect_from_scale_in              = ""
  # scaling_policies                   = ""
  # schedules                          = ""
  # security_groups                    = ""
  # suspended_processes                = ""
  # tag_specifications                 = ""
  # target_group_arns                  = ""
  # termination_policies               = ""
  # use_mixed_instances_policy         = ""
  # warm_pool                          = ""
}

